PRAGMA foreign_keys = ON;
ALTER TABLE cooperatives ADD COLUMN base_tracking_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE cooperatives ADD COLUMN address_city TEXT;
ALTER TABLE cooperatives ADD COLUMN address_state TEXT;
ALTER TABLE establishments ADD COLUMN tracking_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE establishments ADD COLUMN address_json TEXT;
ALTER TABLE establishments ADD COLUMN address_confirmed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE establishments ADD COLUMN address_place_id TEXT;
ALTER TABLE bases ADD COLUMN tracking_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE bases ADD COLUMN address_json TEXT;
ALTER TABLE bases ADD COLUMN address_confirmed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE bases ADD COLUMN address_place_id TEXT;
ALTER TABLE deliveries ADD COLUMN tracking_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE deliveries ADD COLUMN pickup_address_json TEXT;
ALTER TABLE deliveries ADD COLUMN delivery_address_json TEXT;
ALTER TABLE deliveries ADD COLUMN pickup_place_id TEXT;
ALTER TABLE deliveries ADD COLUMN delivery_place_id TEXT;
ALTER TABLE deliveries ADD COLUMN addresses_confirmed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE deliveries ADD COLUMN cash_payment_location TEXT CHECK(cash_payment_location IN ('pickup','delivery'));
ALTER TABLE deliveries ADD COLUMN confirmation_code TEXT;
ALTER TABLE deliveries ADD COLUMN confirmation_verified_at TEXT;
ALTER TABLE deliveries ADD COLUMN cloned_from_delivery_id TEXT REFERENCES deliveries(id);
ALTER TABLE deliveries ADD COLUMN receipt_number TEXT;
ALTER TABLE customer_requests ADD COLUMN pickup_address_json TEXT;
ALTER TABLE customer_requests ADD COLUMN delivery_address_json TEXT;
ALTER TABLE customer_requests ADD COLUMN cash_payment_location TEXT CHECK(cash_payment_location IN ('pickup','delivery'));
ALTER TABLE customer_requests ADD COLUMN confirmation_code TEXT;
ALTER TABLE customer_requests ADD COLUMN receipt_number TEXT;
CREATE TABLE IF NOT EXISTS delivery_ratings(id TEXT PRIMARY KEY,delivery_id TEXT NOT NULL UNIQUE,cooperative_id TEXT NOT NULL,establishment_id TEXT NOT NULL,driver_id TEXT,customer_id TEXT,establishment_score INTEGER NOT NULL CHECK(establishment_score BETWEEN 1 AND 5),driver_score INTEGER CHECK(driver_score BETWEEN 1 AND 5),establishment_tags_json TEXT,driver_tags_json TEXT,comment TEXT,source TEXT NOT NULL DEFAULT 'tracking',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE,FOREIGN KEY(cooperative_id) REFERENCES cooperatives(id),FOREIGN KEY(establishment_id) REFERENCES establishments(id),FOREIGN KEY(driver_id) REFERENCES drivers(id),FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE INDEX IF NOT EXISTS idx_ratings_cooperative ON delivery_ratings(cooperative_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ratings_driver ON delivery_ratings(driver_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ratings_establishment ON delivery_ratings(establishment_id,created_at DESC);
CREATE TABLE IF NOT EXISTS delivery_receipts(id TEXT PRIMARY KEY,delivery_id TEXT NOT NULL UNIQUE,cooperative_id TEXT NOT NULL,customer_id TEXT,receipt_number TEXT NOT NULL UNIQUE,issued_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,snapshot_json TEXT NOT NULL,FOREIGN KEY(delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE,FOREIGN KEY(cooperative_id) REFERENCES cooperatives(id),FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE INDEX IF NOT EXISTS idx_receipts_customer ON delivery_receipts(customer_id,issued_at DESC);
CREATE INDEX IF NOT EXISTS idx_deliveries_weekly_detail ON deliveries(cooperative_id,assigned_driver_id,delivered_at,establishment_id,status);
